error out if task is in git but no tag is found
Now that we use git-archive to produce pristine tarballs, running from
git without $CURRENT_TAG will break, but it was never really supposed to
work in the first place.

Bug: 1136963
Change-Id: I1014db77267f66b531bff21e9b8e2b3aaf384d42

diff --git a/bin/rhts-mk-build-package b/bin/rhts-mk-build-package
--- a/bin/rhts-mk-build-package
+++ b/bin/rhts-mk-build-package
@@ -79,6 +79,16 @@ echo "               VERSION: $VERSION"
 echo "               RELEASE: $RELEASE"
 echo "            SOURCE_DIR: $SOURCE_DIR"
 
+# if we are in git, we need a tag
+if git log -1 &>/dev/null ; then
+    if [[ -z "$CURRENT_TAG" ]] ; then
+        echo "Error: no tags found" >&2
+        echo "(Hint: make tag)" >&2
+        echo "(Hint: to skip version control, move this task outside your git tree)" >&2
+        exit 1
+    fi
+fi
+
 # TMP_DIR: do everything for this run under a unique temp directory
 TMP_DIR=`mktemp -d /tmp/rhts-build-XXXXXXXX` || exit 1
 echo "               TMP_DIR: $TMP_DIR"
