sanity checks for git tags
* When running make tag, ensures that the previous tag is an ancestor of
  the current commit. This should prevent accidentally tagging on
  divergent git branches.
* When running make rpm, ensures that the current tag has been pushed to
  origin (if such a remote is defined). This should prevent forgetting
  to push task changes before uploading to Beaker.

Change-Id: I9db6ff4daa98ac5494f4bb3ac6dda79752a7ed66

diff --git a/bin/rhts-mk-build-package b/bin/rhts-mk-build-package
--- a/bin/rhts-mk-build-package
+++ b/bin/rhts-mk-build-package
@@ -86,6 +86,18 @@ GENERATED_SPECFILE=$GENERATED_SOURCE_DIR/$NAME-$VERSION-$RELEASE.spec
 TARBALL=$GENERATED_SOURCE_DIR/$NAME-$VERSION-$RELEASE.tar.gz
 TESTCOVERAGE=$GENERATED_SOURCE_DIR/testcoverage 
 
+# if we are in git, ensure the tag has been pushed
+if git log -1 &>/dev/null ; then
+    if git config remote.origin.url >/dev/null ; then
+        echo "Verifying that tag is present in remote: $CURRENT_TAG"
+        if ! git ls-remote origin --tags "$CURRENT_TAG" | grep -qF "$CURRENT_TAG" ; then
+            echo "Error: current tag $CURRENT_TAG is not in remote 'origin'"
+            echo "(Hint: git push --tags)"
+            exit 1
+        fi
+    fi
+fi
+
 echo "Creating tarball: $TARBALL"
 tar --exclude "CVS" --exclude ".svn" --exclude ".git" --exclude "rhts-.\*\.rpm" -zcvf $TARBALL --directory $SOURCE_DIR . || exit 1
 
diff --git a/bin/rhts-mk-tag-release b/bin/rhts-mk-tag-release
--- a/bin/rhts-mk-tag-release
+++ b/bin/rhts-mk-tag-release
@@ -30,9 +30,16 @@ fi
 
 
 if git log -1 &>/dev/null; then
+        CURRENT_TAG=`rhts-mk-get-current-tag`
 	NEXT_TAG=`rhts-mk-get-next-tag`
 
 	if [ -n "$NEXT_TAG" ]; then
+                # Sanity check: is the current tag merged into this branch?
+                if ! git rev-list HEAD | grep -q $(git show-ref --hash --tags "$CURRENT_TAG") ; then
+                    echo "Error: current tag $CURRENT_TAG is not an ancestor of HEAD"
+                    echo "(Hint: make sure it is merged into this branch)"
+                    exit 1
+                fi
 		echo Tagging release as $NEXT_TAG
 		git tag $NEXT_TAG
 	else
